version: "3.9"
services:
  db:
    image: postgres:16
    container_name: relay-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: relaydb
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-app:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: relay-auth
    command: node src/authServer.js
    env_file: .env
    ports:
      - "${AUTH_PORT}:4000"
    depends_on:
      - db

  api-app:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: relay-api
    command: node src/server.js
    env_file: .env
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db