apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: relay
type: Opaque
data:
  ACCESS_TOKEN_SECRET: N2Y5NGVhZTFkMDRlNzI1NjRhYzJiNGNhYmJkN2RmZGU0NWFjMjhiZTQ4NTU5MDJjZDc3YThkYmZlYmZmZTZjNjM1MzJiMTMzMDA0MGQ1MjQ5N2FmOWE1MGRiNmM1OGZjYTU5OTc1YzRkYmRlMGE2M2JjYjIxYzliYmI0MTFiZmI=  
  REFRESH_TOKEN_SECRET: YjMyOGE5NTBiNTI4NmE5NDk5OTEyNGM0ZWJlMWNhMDJiOTM1OTE0YjgxNTJiMmM3NWQyMmFlN2YxYzcxNzQzOTcxYWU0MmUwY2FkZjEzM2JiZDBkMzM4MWI5ZDc5YjFiMzI5ZmExZWU0MmE2YzQwMzZmMGRlNmVkZjI1OWE0MjE=
