apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  namespace: relay
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-server
          image: ed18c/relay-app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"     # Requisição base de 0.2 CPU
              memory: "256Mi" # Requisição base de 256 MiB
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: REFRESH_TOKEN_SECRET
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-port
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-db
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5  # Wait 5 seconds before first check
            periodSeconds: 10       # Check every 10 seconds
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15 # Wait 15 seconds before first check
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: relay
  labels:
    app: app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
# apiVersion: v1
# kind: Service
# metadata:
#   name: app-service
#   labels:
#     app: app
# spec:
#   selector:
#     app: app
#   type: NodePort
#   ports:
#     - port: 3000
#       targetPort: 3000
#       nodePort: 30007
