apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: relay
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-server
          image: ed18c/relay-auth:latest
          ports:
            - containerPort: 4000
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: REFRESH_TOKEN_SECRET
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-port
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-db
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: relay
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
# apiVersion: v1
# kind: Service
# metadata:
#   name: auth-service
#   labels:
#     app: auth
# spec:
#   selector:
#     app: auth
#   type: NodePort
#   ports:
#     - port: 4000
#       targetPort: 4000
#       nodePort: 30008

